services:
  git-server:
    image: ghcr.io/ofilla/git-server-docker:latest
    #build: .
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
    - ~/git-server/keys:/git-server/keys
    - ~/git-server/repos:/git-server/repos

